In [1]:
import numpy as np

### array 인덱싱


In [4]:
# 2차원 배열 생성
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# 동일한 출력 결과
print(arr[1,2])
print(arr[1][2])

6
6


In [11]:
# 1차원 array 슬라이싱

# 1부터 9까지의 배열 생성
arr1 = np.arange(1,10)
print(arr1)

# 3번인덱스부터 8번인덱스까지의 값을 12로 변경
arr1[3:8]=12
arr1


[1 2 3 4 5 6 7 8 9]


array([ 1,  2,  3, 12, 12, 12, 12, 12,  9])

In [16]:
# 2차원 array 슬라이싱

# 2차원 배열 생성 (reshape)
arr2 = np.arange(0,50).reshape(10,5)
print(arr2)

# arr2의 0부터 1행까지 1열의 값만 가져오기
print(arr2[0:2,1])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[1 6]
