In [1]:
import numpy as np

In [2]:
# zeros
# 매개변수로 행과 열의 개수를 줘야함
arr_zeros = np.zeros((2,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# ones
# 매개변수로 행과 열의 개수를 줘야함
arr_one = np.ones((3,3))
arr_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# full
# 매개변수로 행열의 개수와 채울 데이터를 지정해줘야함
arr_full = np.full((2,7),"닭")
arr_full

array([['닭', '닭', '닭', '닭', '닭', '닭', '닭'],
       ['닭', '닭', '닭', '닭', '닭', '닭', '닭']], dtype='<U1')

In [9]:
# arange
arr_arange1 = np.arange(1,10)
print(arr_arange1)
arr_arange2 = np.arange(1,10,2)
print(arr_arange2)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [11]:
# random
# 2부터 9까지의 정수 중 랜덤으로 하나의 정수를 생성
arr_randint1 = np.random.randint(2,10)
print(arr_randint1)

# 1부터 9까지의 정수 중 랜덤으로 정수를 뽑는데 3행 4열의 데이터 수만큼 뽑음
arr_randint2 = np.random.randint(1,10, size=(3,4))
arr_randint2

9


array([[4, 8, 6, 6],
       [4, 3, 9, 1],
       [1, 5, 9, 1]])

In [14]:
# array 연산
arr33 = np.array([2,3,4])
arr3 = np.array([1,2,3])
arr4 = np.array([1,2,3,4])

print(arr3*arr3)
print(arr3+arr3)
print(arr3+arr33)

# arr3+arr4 는 불가능
# array의 연산은 array들의 길이가 같은 경우에만 가능하다!

[1 4 9]
[2 4 6]
[3 5 7]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 